Fixed UnicodeEncodeError (print response['title'])
Fixed the following error:

print(': {} [{} - {}]'.format(response['title'], response['startDate'], response['endDate']))
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 53-53: Non-BMP character not supported in Tk

by translating everything outside of the BMP to the replacement character.

Also I put

with open(__output_file__, 'w') as f:
         f.write(json.dumps(offers))

at the end of the main instead of inside the loop, so the program doesn't become an I/O bound program.